[gcp_service_account]
type = "service_account"
project_id = "streamlit-gsheet-app"
private_key_id = "cfc9960c318090293b176d8e59bee9880131b859"
private_key = """-----BEGIN PRIVATE KEY-----
# MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCoN5SHzr8nTu5X
# um9WgeCVba27emMaqyA8rhpZ2+JMle+8OAiG3YR+0rvuJwJxi/CC4RkhAutp3mJH
# 5uKXRzhSUJX6ElZbhZJnsFRE8YdO7zhQ3Mgd32wHPTvv/5En0P/yTlHB6QhN709i
# HACgFVPRWDjdTbRLN78W1p1R7H+QN8qIK60vU8x5KhwpDbURyAS8GPO47JgxFBit
# OdFNkcoxqDtDxws74uDKRbw11pjZXsaPsscJUrgKNv31RqXjBnCy0MHRw4kBLEtn
# 6qklDMy1RCuQarcmutjigKrCR4tiRN1uGqgSquXn/qof+7Xa7BpwvlDfW/VhIgw5
# FP0k3lVXAgMBAAECggEALBLb7LVDqjXpBr1HPKAsypoBAfTwEGWzvZJUPyT4Zt6G
# AIeh3Ewf0ea+7If2APAMZQ47OkX8jjGBCJu61K4JWK/ai7nQPIyDrn0ppyKtNAZD
# eBRQrlsCf+cQVDJewtLkrITOsQKwdVL1NpxloYvU+S2nQHyCd460l3RFpdhUF+HI
# /m6JU/JOX6C1jKwchnsfYeMTXhHjri2UfvKk6Ec+rbmKY+u4ywDPIsHoId83lPbz
# jYCeVP6zQm8isLFkiiEb9L51zMD+AIcv2yMGhlJBFOXHYuDdyvMpG4YPa7WUy6Bo
# XyV7Fv+KapYo6skY11WKLgH7+4llgRLxslgoBUbZAQKBgQDlAmRWCsDe1QLQwJBR
# IrvtQcmFNPk7FFQPSImNLXHzY6VhWzEXrmaAWi0cqYImv2cqq6odfWmnSh/AnfAS
# KTFTo/GzilRyuvaVmb2x1vt6T9dcdSHo+FTHuP1fgwcEHM94/W+FzBDVcxjESS3E
# zTrx8SladRyi+88xKpM15tL0gQKBgQC8Cvs94Uu0MskJwj8GDwwBGXScUDK65yYf
# XHEdRi819BmZtEEFFu/BGTTsAQvNkIeIBoAk8/GmLgmn4eZemQ2aFgGmsGkJo4Gx
# 5PkaaP8RQdMjoUgMyUma7LoZh4uK0QhCcI0p30Ymqz9E1tG0R08f8oqpInhv5LaR
# zh4m4FB91wKBgQDRPstA1th9gjHtXVU/3TXKxgaEoO9srNlVkZilFzX8Bjsw5mrH
# 0YE0m7CGdNdH4jE4ituH0HR99ztl+qlFXsAERVLuEmGw5uWxsWTjHqRukI8dmqTe
# QjDswDk6UPVTK6PiT+bbYKas8Vpa1uZr4H2QXSLE1SbSQLSCnv0dDggIgQKBgHQj
# oCsG5Dfmie5CD6TRVEu1iiUlD0AKlawW7zHycCQ1oD4ja2kWUnwD8oC04LJUyrCD
# u0+Xby+BDaunxR22EAWUA+8M08MFPow97HCYWrkw25QM/7AN/iz2erZb1h6lniFS
# 3Iz4/p3RdKEywJBE3qTPqz5tMM+DBhOlp0/BiVU/AoGAf2GHcYss5TAc4A8vP+sw
# /ramcb4y2rYfz8qsjZskS5H/lSRzWoBgOrWjiBNJFUmhhW5edQpvMQ0EfUTj++YU
# t8Pa4QpiEh5tqpNaKrUw3zZmT0kQIBC95DkJLhjx0LBhksvPHrc6fVph6+/aY/wr
# nbh/yeXfRUqF8GYIlEBMLkc=
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets-access@streamlit-gsheet-app.iam.gserviceaccount.com"
client_id = "110088735136637175133"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-access@streamlit-gsheet-app.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
