[gcp_service_account]
type = "service_account"
project_id = "nexus-creation"
private_key_id = "2995a92875f94e602e4ad68d0f0915348eb1e9f6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQC0R+Pq13Ei45vx
T1svQpFci+3VVkY+ZN64JzJd5ANgsZ3KqwOl6TYNC8SeOcVfTkzj7/tZ1W6KZnre
LbB7Z1SYWS9oH5ANv64CWqxPk9HB0O9eshsWvibIBzl7BN5QhF4/EX6vvdgWTt79
Wv49I5m5NuDh4aXacWr0oXGvg1jQVV3uHM0/k68gozA+nJc+csQYOL+rT8v6pCC3
UXmGOgFJRXRh5bi2ZfAUglJWFMtByv81vXn+b0QJu3zSv7WDAsi0meoJJhE9tyD5
mgOSJ4GeyFNEsJNn1bcdFHl5PG+jOjx+wxSZjWdu3/OvjrLxUtr0DIFCFuDfuDo8
e2fryBCPAgMBAAECgf8wSRD+My1nACkACeNIvKUyTxT1bLcwdm109l/2ChOIME6k
AineX7G8iIP2Q3HVctaLrdSs/zCCnN8HgN/uk9gMBwpNnVm8MtZf3Bx93oiLi3L3
v1X5hbBD0e/PC7p/oxaKAQv19PyelpJnWmas10sZR+ZZ7utSa+wgENlZqP8HEYTA
SXYNqFz4FMpuYF6pUV8uEI238lVyNpN8ulIg49SBBE9um9IYqK3hcgEI/9D3P3zh
ZbdrRI1NHD++8EbwdiAjvk4JsUuY4yYw3dQj8ogDmhwYosg6RlOk4jueX8iOizcs
KiyiuLdfp/691YVXetwKI5v+Tu8W8zG4XyDOcZUCgYEA7RNo/ICNmrxj/Ypt3Ljx
l2RTgDNrysLYQyIb/wV8i3AIHIjBdK2op795WOsL+TeLkDwJ0Zmv0SzUUM9MWX6B
k8TCLt9CRsnmz+H002bYkGM2eT8nGerO/gdXB5A4/VsiY8aMsGgme8duGk/GL4Ao
jL+9nVFkI/iyH4UAZb3Ybr0CgYEAwqvjL62Hsrh128oVlepblx5KjVBwMUirzEhI
Pa8e7/WwSNsP6EsmKdFlgAZW6NIg3eGdBM0ZKczdZsteXZf2Uu0Yp3IVEyvSAqTX
RQ0n2FyMyNqOCR56gqD2x4Zrmxxu0XC5w2Xvv91PneTW12nxrLc86SufeFYYlWoS
6N+C5zsCgYApP+ZVgNyinsLbG5nv/LH0gH1S4h+QQQS18ZpjbgX0kQKoTFc0wP6G
aXdotET6EOMUro2azZ3czGsIwHjtXWiYWHTdCPWUMY8afptFqTBnNwwEXqukA8oO
QyKuazavRoseRy61hvmjMdkDdPvryeXET5xjYgUFiUEc4Nxn13dwFQKBgQCVNZpU
mPVBjxEG/cW9unupQJZz6guUOtczJNP6M5fK5M3RidaPfcoqk0zw6+sBWM3IQ31O
iMWYvGWWvJn/stIijYgwD8kHgLbfP+mgC41W0Nk3ugzUAIB2T1nXZLhlk019SqGX
mzJAJSk5JIVnZtTORURyk/UPDy6Yl00XIPn8sQKBgFiylJ4Cit8lxRj9OHKYBQae
+lqGDcqVCD/Y5f8s9cikMy52Y33D7xcFaWQcWWi38Mf70rcO0DS0rjCmhS7TY3t5
I0SApUrxDvf0BzCWebBKc3XYwgi7G21k0tOkguWpbRkLJV56YYUU7UPXx4SmWcWd
Fy/F2dt7Zsuis2ftLHhS
-----END PRIVATE KEY-----"""
client_email = "nexus-creation-web@nexus-creation.iam.gserviceaccount.com"
client_id = "102097039644027614103"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/nexus-creation-web%40nexus-creation.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
